name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Test with CI
        run: ./gradlew test
      - name: Deploy to Heroku
        run: |
          git fetch --all --unshallow
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:master -f

      #- name: Add coverage to PR
        #id: jacoco
        #uses: madrapps/jacoco-report@v1.3
        #with:
            #paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
            #token: ${{ secrets.TOKEN_GITHUB }}
            #min-coverage-overall: 40
            #min-coverage-changed-files: 60

